#! python
number = int(input("Put first number: "))
number1 = int(input("Put second number: "))
i = "*" 
i = i * number
for j in range(number1 , 0, -1):
    if (j != 0):
        print(i)
    elif (j == 0):
        break
