#! python
import string   
def lower_c():
    stroka = input()
    new_stroka = ''
    for i in stroka:
        if i in string.ascii_uppercase:
            j = string.ascii_uppercase.index(i)
            new_stroka+=string.ascii_lowercase[j]
        else:
            new_stroka+=i
    print(new_stroka)
    
def ambi_c():
    stroka = input()
    new_stroka = ''
    for i in stroka:
        if i in string.ascii_uppercase:
            j = string.ascii_uppercase.index(i)
            new_stroka+=string.ascii_lowercase[j]
        elif i in string.ascii_lowercase:
            j = string.ascii_lowercase.index(i)
            new_stroka+=string.ascii_uppercase[j]
        else:
            new_stroka+=i
    print(new_stroka)   
    
ambi_c()
